src_file: fix audio track indexing
`track` argument to `AudioSource()` needs to be an int, not a Track.
Otherwise:

    Traceback (most recent call last):
      File "test.py", line 4, in <module>
        f.get_audio()
      File "vsmuxtools/utils/source.py", line 207, in get_audio
        nodes.append(core.bs.AudioSource(str(f.resolve()), absolute, **kwargs))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "src/cython/vapoursynth.pyx", line 3107, in vapoursynth.Function.__call__
      File "src/cython/vapoursynth.pyx", line 3098, in vapoursynth.Function.__call__
      File "src/cython/vapoursynth.pyx", line 1071, in vapoursynth.typedDictToMap
    TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Track'

Minimal repro:

    from vsmuxtools import src_file

    f = src_file(r"/path/to/file/with/audio.mkv")
    f.get_audio()